<?php
// defining the menu list
$menuItem= (object) array (
			(object) array ( 'path'=>'home','text'=>'Accueil'),
			(object) array ( 'path'=>'about','text'=>'A propos'),
			(object) array ( 'path'=>'services','text'=>'Nos services'),
			(object) array ( 'path'=>'gallery','text'=>'Nos references'),
			(object) array ( 'path'=>'contact','text'=>'Nous contacter')
			);

?>

<div id="templatemo_header_wrapper">
	<div id="templatemo_header">

		<div id="site_title">
            <h1><a href="index.html">
                <strong>JIS Computing</strong>
                <span>free css templates</span>
            </a></h1>
        </div>

        <div id="templatemo_menu">
            <ul>
            <?php
            foreach ($menuItem as $k=>$v){
            ?>
            	<li><a href="/<?php echo $v->path;?>" <?php  if($page_requested==$v->path) echo 'class="current"'; ?> ><?php echo $v->text;?></a></li>
			<?php
            }

            ?>
            </ul>
    	</div> <!-- end of templatemo_menu -->
        <div class="cleaner"></div>
	</div> <!-- end of header -->
</div> <!-- end of header_wrapper -->