    </div>
    <!--End pagewrapper-->

    <!-- Scroll Top Button -->
    <button class="scroll-top scroll-to-target" data-target="html"><i class="icofont-arrow-up"></i></button>

  <!-- jQuery Plugins -->
    <script src="<?php echo $iniObj->UIPath; ?>/js/bootstrap.min.js"></script>
    <script src="<?php echo $iniObj->UIPath; ?>/js/jquery.magnific-popup.min.js"></script>
    <script src="<?php echo $iniObj->UIPath; ?>/js/leaflet.min.js"></script>
    <script src="<?php echo $iniObj->UIPath; ?>/js/slick.min.js"></script>

    <!-- Custom Script -->
    <script src="<?php echo $iniObj->UIPath; ?>js/script.js"></script>

</body>

<!-- Mirrored from live.envalab.com/html/envotek/ by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 26 May 2021 14:19:50 GMT -->
</html>