   <!-- Preloader -->
   <!-- <div class="preloader"></div> -->

   <!-- START Main Header -->
   <header class="main-header">

     <!-- Header-Upper -->
     <div class="header-upper">
       <div class="container clearfix">

         <div class="header-inner d-lg-flex align-items-center">

           <div class="logo-outer d-flex align-items-center">
             <div class="logo"><a href="<?php $lib->customerSite ?>/"><img src="<?php echo $iniObj->UIPath; ?>/images/logo.png" alt="Logo" /></a></div>
           </div>

           <div class="nav-outer clearfix ml-lg-auto mr-lg-auto">
             <!-- Main Menu -->
             <nav class="main-menu navbar-expand-lg">
               <div class="navbar-header clearfix">
                 <!-- Toggle Button -->
                 <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                   <span class="icon-bar"></span>
                   <span class="icon-bar"></span>
                   <span class="icon-bar"></span>
                 </button>
               </div>

               <div class="navbar-collapse collapse clearfix">
                 <ul class="navigation clearfix">
                   <li class="current-menu-item"><a href="<?php $lib->customerSite ?>/">Home</a></li>
                   <li><a href="<?php $lib->customerSite ?>/about">About</a></li>
                   <li><a href="<?php $lib->customerSite ?>/service">Service</a></li>
                   <li><a href="<?php $lib->customerSite ?>/project">Project</a></li>
                   <li><a href="<?php $lib->customerSite ?>/blog">Blog</a></li>
                   <li><a href="<?php $lib->customerSite ?>/contact">Contact</a></li>
                 </ul>
               </div>
             </nav>
             <!-- Main Menu END -->
           </div>

           <div class="menu-btn">
             <a href="<?php $lib->customerSite ?>/devis" class="btn theme-btn">Demande de devis <i class="icofont-arrow-right"></i></a>
           </div>

         </div>
       </div>
     </div>
     <!-- END Header Upper -->
   </header>
   <!-- END Main Header -->