<div id="templatemo_footer_wrapper">
	<div id="templatemo_footer">

    	<div class="footer_box">

        	<h3>Partners</h3>

            <ul class="footer_menu">
                <li><a href="http://www.templatemo.com/page/1" target="_parent">Free CSS Templates</a></li>
                <li><a href="http://www.flashmo.com/page/1" target="_parent">Free Flash Templates</a></li>
                <li><a href="http://www.webdesignmo.com/blog" target="_parent">Web Design Blog</a></li>
                <li><a href="http://www.koflash.com">Best Flash Gallery</a></li>
            </ul>

        </div>

        <div class="footer_box">

            <div class="footer_menu">

                <h3>Navigation</h3>

                <ul class="footer_menu">

					<?php
		            	foreach ($menuItem as $k => $v){
		            ?>
		            	<li><a href="/<?php echo $v->path;?>" ><?php echo $v->text;?></a></li>
					<?php
		            	}
	            	?>
                </ul>

            </div>
		</div>

        <div class="footer_box">

            <div class="footer_menu">

              <h3>About Us</h3>

                <img src="images/templatemo_image_04.jpg" alt="about us" />
                <p>Nullam ultrices tempor nisi, ac egestas diam aliquam  mattis adipiscing imperdiet.</p>

                <div class="button"><a href="#">Read More</a></div>

            </div>

        </div>

    	<div class="cleaner"></div>
    </div> <!-- end of footer -->
</div> <!-- end of footer wrapper -->

<div id="templatemo_copyright_wrapper">
	<div id="templatemo_copyright">

		Copyright © 2048 <a href="#">Your Company Name</a> |
        Designed by <a href="http://www.templatemo.com" target="_parent">Free CSS Templates</a> |
        Validate <a href="http://validator.w3.org/check?uri=referer">XHTML</a> &amp; <a href="http://jigsaw.w3.org/css-validator/check/referer">CSS</a>

    </div> <!-- end of templatemo_copyright -->
</div> <!-- end of copyright wrapper -->
</body>
</html>