<?php header('Expires: ' . gmdate('D, d M Y H:i:s \G\M\T', time() + $iniObj->headerReferesh)); ?>

<!DOCTYPE html>
<html lang="en">

<!-- Mirrored from live.envalab.com/html/envotek/ by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 26 May 2021 14:18:56 GMT -->

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0">
    <title>Welcome || Envotek - IT Solution and Services HTML5 Template</title>

    <!-- Fav Icons -->
    <link rel="shortcut icon" href="<?php echo $iniObj->UIPath; ?>/images/favicon.png" type="image/x-icon">

    <!-- Google Fonts -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,300;0,400;0,500;0,700;1,300;1,400;1,500&amp;display=swap" />

    <!-- Stylesheets -->
    <link rel="stylesheet" href="<?php echo $iniObj->UIPath; ?>/css/magnific-popup.min.css" />
    <link rel="stylesheet" href="<?php echo $iniObj->UIPath; ?>/css/bootstrap.min.css" />
    <link rel="stylesheet" href="<?php echo $iniObj->UIPath; ?>/css/icofont.min.css" />
    <link rel="stylesheet" href="<?php echo $iniObj->UIPath; ?>/css/spacing.min.css" />
    <link rel="stylesheet" href="<?php echo $iniObj->UIPath; ?>/css/leaflet.min.css" />
    <link rel="stylesheet" href="<?php echo $iniObj->UIPath; ?>/css/slick.min.css" />
    <link rel="stylesheet" href="<?php echo $iniObj->UIPath; ?>/css/menu.css" />
    <!-- Main Style CSS -->
    <link rel="stylesheet" href="<?php echo $iniObj->UIPath; ?>/css/style.css" />
    <!-- Responsive CSS -->
    <link rel="stylesheet" href="<?php echo $iniObj->UIPath; ?>/css/responsive.css" />
    
    <script src="<?php echo $iniObj->UIPath; ?>/js/jquery-3.5.1.min.js"></script>

    <!--[if lt IE 9]><script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.js"></script><![endif]-->
</head>

<body>
    <div class="page-wrapper">