    <!-- START Page Banner -->
    <section class="page-banner">
        <div class="container">
            <div class="banner-content text-center">
                <h2>About Us</h2>
                <div class="page-breadcrumb">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="index-2.html">Home</a></li>
                            <li class="breadcrumb-item active" aria-current="page">About</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </section>
    <!-- END Page Banner -->

    <!-- START About Us Section -->
    <section class="about-us pt-120 rpt-100">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-6">
                    <div class="about-left">
                        <div class="experience-years">
                            <h1>25+</h1>
                            <h4>Years Experience</h4>
                        </div>
                        <div class="about-image">
                            <img src="<?php echo $iniObj->UIPath; ?>/images/about/about-img1.jpg" alt="About Image" />
                        </div>
                        <div class="about-image-two">
                            <img src="<?php echo $iniObj->UIPath; ?>/images/about/about-img2.jpg" alt="About Image" />
                        </div>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="about-us-content">
                        <div class="section-title">
                            <span>About Us</span>
                            <h2>We are the best world IT Company. More than 25 years of experience.</h2>
                        </div>
                        <p>It has survived not only five centuries, but also the leap into electroni typesetting, remaining essentially unchanged. It was popularised the 1960s with the release and more recent.</p>
                        <blockquote>It has survived not only five centuries, but also the leap into the typesetting, remaining essentially unchanged. It was popular of the release and more recent.</blockquote>
                        <p>It has survived not only five centuries, but also the leap into electroni typesetting, remaining essentially unchanged. It was popularised the 1960s with the release and more recent.</p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- END About Us Section -->

    <!-- START About Page Choose Us Section -->
    <section class="about-choose-us pt-120 rpt-100 pb-115 rpb-100">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="about-video-area">
                        <a class="video-play mfp-iframe" href="https://www.youtube.com/watch?v=aFWhf2wjJYo&amp;list=PLUoqTnNH-2XxOt7UsKlTqbfrA2ucGosCR">
                            <i class="icofont-ui-play"></i>
                        </a>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-6">
                    <div class="about-choose-us-left">
                        <div class="section-title">
                            <h2>Some Reason Why You Should Choose Us!</h2>
                        </div>
                        <div class="chooseus-list">
                            <div class="row">
                                <div class="col-sm-6">
                                    <ul>
                                        <li><i class="icofont-check"></i> Simplify Communication</li>
                                        <li><i class="icofont-check"></i> Eliminate Repeat Entry</li>
                                    </ul>
                                </div>
                                <div class="col-sm-6">
                                    <ul>
                                        <li><i class="icofont-check"></i> 24/7 Customer Service</li>
                                        <li><i class="icofont-check"></i> Expert Team Members</li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <blockquote>It has survived not only five centuries, but also the leap into the typesetting, remaining essentially unchanged. It was popular of the release and more recent.</blockquote>
                        <p>It has survived not only five centuries, but also the leap into electroni typesetting, remaining essentially unchanged. It was popularised the 1960s with the release and more recent.</p>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="about-choose-us-right">
                        <h2>We are Creative & Professional <span>Our Mission And Vission.</span></h2>
                        <p>It has survived not only five centuries, but also the leap into electroni typesetting, remaining essentially unchanged. It was popularised the 1960s with the release and more recent.</p>
                        <p>It has survived not only five centuries, but also the leap into electroni typesetting, remaining essentially unchanged. It was popularised the 1960s with the release and more recent.</p>
                        <a href="about.html" class="btn theme-btn">Read More <i class="icofont-double-right"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- END About Page Choose Us Section -->

    <!-- START Partner Section -->
    <div class="partner-section">
        <div class="container">
            <div class="partners-group">
                <div class="row">
                    <div class="col-md-3 col-6">
                        <div class="partner-logo">
                            <a href="https://www.domain.com/">
                                <img src="<?php echo $iniObj->UIPath; ?>/images/partners/partner-logo1.png" alt="Partner Logo" />
                            </a>
                        </div>
                    </div>
                    <div class="col-md-3 col-6">
                        <div class="partner-logo">
                            <a href="https://www.domain.com/">
                                <img src="<?php echo $iniObj->UIPath; ?>/images/partners/partner-logo2.png" alt="Partner Logo" />
                            </a>
                        </div>
                    </div>
                    <div class="col-md-3 col-6">
                        <div class="partner-logo">
                            <a href="https://www.domain.com/">
                                <img src="<?php echo $iniObj->UIPath; ?>/images/partners/partner-logo3.png" alt="Partner Logo" />
                            </a>
                        </div>
                    </div>
                    <div class="col-md-3 col-6">
                        <div class="partner-logo">
                            <a href="https://www.domain.com/">
                                <img src="<?php echo $iniObj->UIPath; ?>/images/partners/partner-logo4.png" alt="Partner Logo" />
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- END Partner Section -->

    <!-- START Team Section -->
    <section class="team-section pt-110 rpt-90 pb-120 rpb-60">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="section-title text-center">
                        <span>Team Members</span>
                        <h2>Our Professional<br /> Team Members</h2>
                    </div>
                </div>
            </div>
            <div class="team-wrap">
                <div class="border-shap"></div>
                <div class="team-member">
                    <div class="member-image">
                        <img src="<?php echo $iniObj->UIPath; ?>/images/team/team-member1.jpg" alt="Team Member Image" />
                    </div>
                    <div class="member-desc">
                        <h5>Sharyl Etheridge</h5>
                        <span>Consultant Officer</span>
                    </div>
                </div>
                <div class="team-member">
                    <div class="member-image">
                        <img src="<?php echo $iniObj->UIPath; ?>/images/team/team-member2.jpg" alt="Team Member Image" />
                    </div>
                    <div class="member-desc">
                        <h5>Brittaney Hickson</h5>
                        <span>Web Developer</span>
                    </div>
                </div>
                <div class="team-member">
                    <div class="member-image">
                        <img src="<?php echo $iniObj->UIPath; ?>/images/team/team-member3.jpg" alt="Team Member Image" />
                    </div>
                    <div class="member-desc">
                        <h5>Rosalina Sheldon</h5>
                        <span>UI Designer</span>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- END Team Section -->

    <!-- START Call To Action -->
    <section class="cta-section pb-120 rpb-100 bg-white">
        <div class="container">
            <div class="contact-withus">
                <div class="row">
                    <div class="col-lg-7">
                        <div class="contact-withus-content">
                            <h3>Contact With Us.<br /> To Require a Detailed Analysis of Your Plan.</h3>
                        </div>
                    </div>
                    <div class="col-lg-5">
                        <div class="contact-withus-num">
                            <a class="contact-number" href="callto:0095788394">+00 95 788 394</a>
                            <a href="contact.html" class="btn theme-btn">Contact Today<i class="icofont-double-right"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- END Call To Action -->