   <!-- START Main Footer -->
   <footer class="main-footer">
     <div class="footer-wrap pt-115 rpt-95 pb-60 rpb-40">
       <div class="container">
         <div class="row">
           <div class="col-lg-3 col-sm-6">
             <div class="footer-widget quick-links">
               <h4>Quick Links</h4>
               <ul>
                 <li>
                   <a href="#"><i class="icofont-double-right"></i>Pick up locations</a>
                 </li>
                 <li>
                   <a href="#"><i class="icofont-double-right"></i>Terms of Payment</a>
                 </li>
                 <li>
                   <a href="#"><i class="icofont-double-right"></i>Privacy Policy</a>
                 </li>
                 <li>
                   <a href="#"><i class="icofont-double-right"></i>Where to Find Us</a>
                 </li>
                 <li>
                   <a href="#"><i class="icofont-double-right"></i>Privacy Policy</a>
                 </li>
               </ul>
             </div>
           </div>
           <div class="col-lg-3 col-sm-6">
             <div class="footer-widget latest-post">
               <h4>Latest Post</h4>
               <div class="post-item">
                 <div class="post-image">
                   <a href="<?php echo $iniObj->UIPath; ?>/blog"> <img src="<?php echo $iniObj->UIPath; ?>/images/footer/post1.png" alt="Latest Post Image" /></a>
                 </div>
                 <div class="post-content">
                   <h6><a href="<?php $lib->customerSite ?>/blog">We carry more than just good coding skills.</a></h6>
                   <span>22.01.2021</span>
                 </div>
               </div>
               <div class="post-item">
                 <div class="post-image">
                   <a href="<?php $lib->customerSite ?>/blog"> <img src="<?php echo $iniObj->UIPath; ?>/images/footer/post2.png" alt="Latest Post Image" /></a>
                 </div>
                 <div class="post-content">
                   <h6><a href="<?php $lib->customerSite ?>/blog">We carry more than just good coding skills.</a></h6>
                   <span>22.01.2021</span>
                 </div>
               </div>
             </div>
           </div>
           <div class="col-lg-3 col-sm-6">
             <div class="footer-widget quick-links support">
               <h4>Support</h4>
               <ul>
                 <li>
                   <a href="#"><i class="icofont-double-right"></i>Forum Support</a>
                 </li>
                 <li>
                   <a href="#"><i class="icofont-double-right"></i>Help & FAQ</a>
                 </li>
                 <li>
                   <a href="#"><i class="icofont-double-right"></i>Pricing and Plans</a>
                 </li>
                 <li>
                   <a href="#"><i class="icofont-double-right"></i>Cookies Policy</a>
                 </li>
                 <li>
                   <a href="#"><i class="icofont-double-right"></i>Help & FAQ</a>
                 </li>
               </ul>
             </div>
           </div>
           <div class="col-lg-3 col-sm-6">
             <div class="footer-widget quick-links company">
               <h4>Company</h4>
               <ul>
                 <li>
                   <a href="about.html"><i class="icofont-double-right"></i>About Us</a>
                 </li>
                 <li>
                   <a href="#"><i class="icofont-double-right"></i>Leadership Team</a>
                 </li>
                 <li>
                   <a href="#"><i class="icofont-double-right"></i>Case Studies</a>
                 </li>
                 <li>
                   <a href="contact.html"><i class="icofont-double-right"></i>Locations</a>
                 </li>
                 <li>
                   <a href="#"><i class="icofont-double-right"></i>Team Members</a>
                 </li>
               </ul>
             </div>
           </div>
         </div>
       </div>
     </div>
     <!-- Copyright Area -->
     <div class="copy-right-area">
       <div class="container">
         <div class="copy-right-text text-center">
           <p><span>Copyright</span> © 2021 JISCOMPUTING | All Rights Reserved</p>
         </div>
       </div>
     </div>
   </footer>
   <!-- END Main Footer -->

   </div>
   <!--End pagewrapper-->