 <!-- START Page Banner -->
 <section class="page-banner">
     <div class="container">
         <div class="banner-content text-center">
             <h2>Contact Us</h2>
             <div class="page-breadcrumb">
                 <nav aria-label="breadcrumb">
                     <ol class="breadcrumb">
                         <li class="breadcrumb-item"><a href="index-2.html">Home</a></li>
                         <li class="breadcrumb-item active" aria-current="page">Pages</li>
                     </ol>
                 </nav>
             </div>
         </div>
     </div>
 </section>
 <!-- END Page Banner -->

 <!-- START Contact Section -->
 <section class="contact-section py-120 rpy-100">
     <div class="container">
         <div class="row">
             <div class="col-lg-5">
                 <div class="get-touch-left">
                     <div class="info-box">
                         <div class="info-icon">
                             <i class="icofont-google-map"></i>
                         </div>
                         <div class="info-details">
                             <p>61 South Big Rock Cove Lane Lake Zurich, Villad 60047</p>
                         </div>
                     </div>
                     <div class="info-box">
                         <div class="info-icon">
                             <i class="icofont-phone"></i>
                         </div>
                         <div class="info-details">
                             <a href="callto:88999666444">+88-999-666-444</a>
                             <a href="callto:88999333555">+88-999-333-555</a>
                         </div>
                     </div>
                     <div class="info-box">
                         <div class="info-icon">
                             <i class="icofont-email"></i>
                         </div>
                         <div class="info-details">
                             <a href="mailto:yourmail@domain.com">yourmail@domain.com</a>
                             <a href="mailto:support@domain.com">support@domain.com</a>
                         </div>
                     </div>
                     <div class="get-touch-img">
                         <img src="<?php echo $iniObj->UIPath; ?>/images/get-touch-img.png" alt="Get Touch Image" />
                     </div>
                 </div>
             </div>
             <div class="col-lg-7">
                 <div class="get-touch-right">
                     <h3>Get in Touch:</h3>
                     <div class="contact-form">
                         <form action="#">
                             <div class="form-row">
                                 <div class="col-12">
                                     <input type="text" class="form-control custom-input" id="name" name="name" value="" placeholder="Name:" required />
                                 </div>
                                 <div class="col-12">
                                     <input type="email" class="form-control custom-input" id="email" name="email" value="" placeholder="Email:" required />
                                 </div>
                                 <div class="col-12">
                                     <input type="text" class="form-control custom-input" id="number" name="number" value="" placeholder="Phone:" />
                                 </div>
                                 <div class="col-12">
                                     <textarea class="form-control custom-textarea" id="message:" name="message:" rows="7" placeholder="Message:" required></textarea>
                                 </div>
                             </div>
                             <div class="text-center col-12">
                                 <button type="submit" class="btn submit">Submit Comment <i class="icofont-arrow-right"></i></button>
                             </div>
                         </form>
                     </div>
                 </div>
             </div>
         </div>
     </div>
 </section>
 <!-- END Contact Section -->

 <!--==================================================================== 
            Start Map Section
        =====================================================================-->
 <div class="contact-map">
     <div class="map-inner">
         <div class="map" id="map"></div>
     </div>
 </div>
 <!--==================================================================== 
            End Map Section
        =====================================================================-->