 <!-- START Hero Section -->
 <section class="hero-section">
            <div class="hero-shape">
                <img src="<?php echo $iniObj->UIPath; ?>/images/hero/hero-shape.png" alt="Hero Shape Image" />
            </div>
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <div class="hero-content">
                            <h1>IT Management Service & Support for Your Business.</h1>
                            <p>Keep your business safe & ensure high availability.</p>
                            <a href="servicedetails.html" class="btn theme-btn">Find Solusion <i class="icofont-double-right"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- END Hero Section -->

        <!-- START Service Section -->
        <section class="service-section pt-110 rpt-90 pb-70 rpb-100">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <div class="section-title text-center">
                            <span>Our Services</span>
                            <h2>Choose Service For Manage Your Business</h2>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-8 col-xl-9">
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="service-item">
                                    <div class="serv-iconimg">
                                        <img src="<?php echo $iniObj->UIPath; ?>/images/service/serv-icon1.png" alt="Service Icon" />
                                    </div>
                                    <div class="serv-content">
                                        <h5><a href="servicedetails.html">IT Management<br /> Services.</a></h5>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="service-item">
                                    <div class="serv-iconimg">
                                        <img src="<?php echo $iniObj->UIPath; ?>/images/service/serv-icon2.png" alt="Service Icon" />
                                    </div>
                                    <div class="serv-content">
                                        <h5><a href="servicedetails.html">Backup & Data<br /> Recovery.</a></h5>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="service-item">
                                    <div class="serv-iconimg">
                                        <img src="<?php echo $iniObj->UIPath; ?>/images/service/serv-icon3.png" alt="Service Icon" />
                                    </div>
                                    <div class="serv-content">
                                        <h5><a href="servicedetails.html">Cloud Managed<br /> Services.</a></h5>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="service-item">
                                    <div class="serv-iconimg">
                                        <img src="<?php echo $iniObj->UIPath; ?>/images/service/serv-icon4.png" alt="Service Icon" />
                                    </div>
                                    <div class="serv-content">
                                        <h5><a href="servicedetails.html">Cyber Security<br /> Services.</a></h5>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="service-item">
                                    <div class="serv-iconimg">
                                        <img src="<?php echo $iniObj->UIPath; ?>/images/service/serv-icon5.png" alt="Service Icon" />
                                    </div>
                                    <div class="serv-content">
                                        <h5><a href="servicedetails.html">Software<br /> Development.</a></h5>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="service-item">
                                    <div class="serv-iconimg">
                                        <img src="<?php echo $iniObj->UIPath; ?>/images/service/serv-icon6.png" alt="Service Icon" />
                                    </div>
                                    <div class="serv-content">
                                        <h5><a href="servicedetails.html">Big Data And<br /> Analytics.</a></h5>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 col-xl-3">
                        <div class="service-img">
                            <div class="service-details-btn">
                                <a href="servicedetails.html" class="btn theme-btn">More Services<i class="icofont-double-right"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- END Service Section -->

        <!-- START Partner Section -->
        <div class="partner-section">
            <div class="container">
                <div class="partners-group">
                    <div class="row">
                        <div class="col-md-3 col-6">
                            <div class="partner-logo">
                                <a href="https://www.domain.com/">
                                    <img src="<?php echo $iniObj->UIPath; ?>/images/partners/partner-logo1.png" alt="Partner Logo" />
                                </a>
                            </div>
                        </div>
                        <div class="col-md-3 col-6">
                            <div class="partner-logo">
                                <a href="https://www.domain.com/">
                                    <img src="<?php echo $iniObj->UIPath; ?>/images/partners/partner-logo2.png" alt="Partner Logo" />
                                </a>
                            </div>
                        </div>
                        <div class="col-md-3 col-6">
                            <div class="partner-logo">
                                <a href="https://www.domain.com/">
                                    <img src="<?php echo $iniObj->UIPath; ?>/images/partners/partner-logo3.png" alt="Partner Logo" />
                                </a>
                            </div>
                        </div>
                        <div class="col-md-3 col-6">
                            <div class="partner-logo">
                                <a href="https://www.domain.com/">
                                    <img src="<?php echo $iniObj->UIPath; ?>/images/partners/partner-logo4.png" alt="Partner Logo" />
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- END Partner Section -->

        <!-- START Choose Us Section -->
        <section class="chooseus-section pt-120 rpt-100 pb-120 rpb-95">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-6">
                        <div class="chooseus-left-content">
                            <div class="experience-years">
                                <h1>25+</h1>
                                <h4>Years Experience</h4>
                            </div>
                            <div class="chooseus-img">
                                <img src="<?php echo $iniObj->UIPath; ?>/images/chooseus/chooseus-img.jpg" alt="Choose Us Image" />
                            </div>
                            <div class="experience-content">
                                <blockquote>It has survived not only five centuries, but also the leap into electronic types remaining essentially unchanged.</blockquote>
                                <div class="quotation-icon">
                                    <img src="<?php echo $iniObj->UIPath; ?>/images/chooseus/quotation-icon.png" alt="Quotation" />
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="chooseus-right-content">
                            <div class="section-title">
                                <span>Why Choose Us!</span>
                                <h2>Some Reason Why You Should Choose Us!</h2>
                            </div>
                            <div class="chooseus-list">
                                <div class="row">
                                    <div class="col-sm-6">
                                        <ul>
                                            <li><i class="icofont-check"></i> Simplify Communication</li>
                                            <li><i class="icofont-check"></i> Eliminate Repeat Entry</li>
                                        </ul>
                                    </div>
                                    <div class="col-sm-6">
                                        <ul>
                                            <li><i class="icofont-check"></i> 24/7 Customer Service</li>
                                            <li><i class="icofont-check"></i> Expert Team Members</li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                            <blockquote>It has survived not only five centuries, but also the leap into the typesetting, remaining essentially unchanged. It was popular of the release and more recent.</blockquote>
                            <p>It has survived not only five centuries, but also the leap into electroni typesetting, remaining essentially unchanged. It was popularised the 1960s with the release and more recent.</p>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- END Choose Us Section -->

        <!-- START Project Section -->
        <section class="project-section pt-110 rpt-90 pb-60">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <div class="section-title text-center">
                            <span>Success Stories</span>
                            <h2>Successfully Complete All Case of Clients.</h2>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-8">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="project-item">
                                    <div class="project-image">
                                        <img src="<?php echo $iniObj->UIPath; ?>/images/project/project1.jpg" alt="Project Image" />
                                    </div>
                                    <div class="project-content">
                                        <a href="projectdetails.html" class="project-icon">
                                            <i class="icofont-arrow-right"></i>
                                        </a>
                                        <h5><a href="projectdetails.html">IT Management Services.</a></h5>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="project-item">
                                    <div class="project-image">
                                        <img src="<?php echo $iniObj->UIPath; ?>/images/project/project2.jpg" alt="Project Image" />
                                    </div>
                                    <div class="project-content">
                                        <a href="projectdetails.html" class="project-icon">
                                            <i class="icofont-arrow-right"></i>
                                        </a>
                                        <h5><a href="projectdetails.html">Branding Development.</a></h5>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="project-item">
                                    <div class="project-image">
                                        <img src="<?php echo $iniObj->UIPath; ?>/images/project/project3.jpg" alt="Project Image" />
                                    </div>
                                    <div class="project-content">
                                        <a href="projectdetails.html" class="project-icon">
                                            <i class="icofont-arrow-right"></i>
                                        </a>
                                        <h5><a href="projectdetails.html">Technology Prototyping.</a></h5>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="project-item">
                                    <div class="project-image">
                                        <img src="<?php echo $iniObj->UIPath; ?>/images/project/project4.jpg" alt="Project Image" />
                                    </div>
                                    <div class="project-content">
                                        <a href="projectdetails.html" class="project-icon">
                                            <i class="icofont-arrow-right"></i>
                                        </a>
                                        <h5><a href="projectdetails.html">UI/UX Design Strategy.</a></h5>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="project-item project-right-item">
                            <div class="project-content">
                                <a href="projectdetails.html" class="project-icon">
                                    <i class="icofont-arrow-right"></i>
                                </a>
                                <h5><a href="projectdetails.html">Product Consultation.</a></h5>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- END Project Section -->

        <!-- START Testimonial Section -->
        <section class="testimonial-section pb-105 rpb-85">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <div class="section-title text-center">
                            <span>Testimonial</span>
                            <h2>What People Say<br /> About Our Company Services.</h2>
                        </div>
                    </div>
                </div>
                <div class="testimonial-wrap">
                    <div class="testimonial-item">
                        <div class="testimonial-inner">
                            <div class="quotation-img">
                                <img src="<?php echo $iniObj->UIPath; ?>/images/testimonial/quotation-icon.png" alt="Quotation" />
                            </div>
                            <div class="testimonial-content">
                                <p>It has survived not only five centuries, but also the leap into typesetting, remaining essentially unchanged. It popular of the release and more recent five and centurbut also these tesetng remaining essentially.</p>
                            </div>
                        </div>
                        <div class="testimonial-imgbox">
                            <div class="testimonial-img">
                                <img src="<?php echo $iniObj->UIPath; ?>/images/testimonial/testimonial1.png" alt="Author Image" />
                            </div>
                            <div class="testimonial-imgdetails">
                                <h5>Ronnie Aguilar</h5>
                                <span>Web Developer</span>
                            </div>
                        </div>
                    </div>
                    <div class="testimonial-item">
                        <div class="testimonial-inner">
                            <div class="quotation-img">
                                <img src="<?php echo $iniObj->UIPath; ?>/images/testimonial/quotation-icon.png" alt="Quotation" />
                            </div>
                            <div class="testimonial-content">
                                <p>Remaining essentially unchanged. It popular of the release and more recent five and centurbut also today these tesetng remaining essentially, t has survived not only five centuries, but also the leap into typesetting.</p>
                            </div>
                        </div>
                        <div class="testimonial-imgbox">
                            <div class="testimonial-img">
                                <img src="<?php echo $iniObj->UIPath; ?>/images/testimonial/testimonial2.png" alt="Author Image" />
                            </div>
                            <div class="testimonial-imgdetails">
                                <h5>Darla Harmon</h5>
                                <span>UX Designer</span>
                            </div>
                        </div>
                    </div>
                    <div class="testimonial-item">
                        <div class="testimonial-inner">
                            <div class="quotation-img">
                                <img src="<?php echo $iniObj->UIPath; ?>/images/testimonial/quotation-icon.png" alt="Quotation" />
                            </div>
                            <div class="testimonial-content">
                                <p>It has survived not only five centuries, but also the leap into typesetting, remaining essentially unchanged. It popular of the release and more recent five and centurbut also these tesetng remaining essentially.</p>
                            </div>
                        </div>
                        <div class="testimonial-imgbox">
                            <div class="testimonial-img">
                                <img src="<?php echo $iniObj->UIPath; ?>/images/testimonial/testimonial1.png" alt="Author Image" />
                            </div>
                            <div class="testimonial-imgdetails">
                                <h5>Ronnie Aguilar</h5>
                                <span>Web Developer</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- END Testimonial Section -->

        <!-- START Call To Action -->
        <section class="cta-section pb-120 rpb-100">
            <div class="container">
                <div class="contact-withus">
                    <div class="row">
                        <div class="col-lg-7">
                            <div class="contact-withus-content">
                                <h3>Contact With Us.<br /> To Require a Detailed Analysis of Your Plan.</h3>
                            </div>
                        </div>
                        <div class="col-lg-5">
                            <div class="contact-withus-num">
                                <a class="contact-number" href="callto:0095788394">+00 95 788 394</a>
                                <a href="contact.html" class="btn theme-btn">Contact Today<i class="icofont-double-right"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- END Call To Action -->

        <!-- START Blog Section -->
        <section class="blog-section pt-110 rpt-90 pb-70">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <div class="section-title text-center">
                            <span>Blog Post</span>
                            <h2>Some Latest Articles From Our News Feed.</h2>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-6">
                        <div class="blog-item">
                            <div class="blog-image" style="background-image: url(<?php echo $iniObj->UIPath; ?>/images/blog/blog1.jpg);"></div>
                            <div class="blog-content">
                                <span class="date">22 January, 2021</span>
                                <h5><a href="blogdetails.html">It uses a dictionary of over combined handful.</a></h5>
                                <p>It has survived not only five centuries typesetting remaining essentially was the release more recent.</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="blog-item">
                            <div class="blog-image" style="background-image: url(<?php echo $iniObj->UIPath; ?>/images/blog/blog2.jpg);"></div>
                            <div class="blog-content">
                                <span class="date">02 March, 2021</span>
                                <h5><a href="blogdetails.html">Efficiently monetize models transparent sources.</a></h5>
                                <p>Recent survived not only five centuries typesetting remaining essentially was the release mor.</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="blog-item">
                            <div class="blog-image" style="background-image: url(<?php echo $iniObj->UIPath; ?>/images/blog/blog3.jpg);"></div>
                            <div class="blog-content">
                                <span class="date">08 March, 2021</span>
                                <h5><a href="blogdetails.html">Market Insights To Manage People Related Costs.</a></h5>
                                <p>Typesetting It has survived not only five centuries remaining essentially was the release more recent.</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="blog-item">
                            <div class="blog-image" style="background-image: url(<?php echo $iniObj->UIPath; ?>/images/blog/blog4.jpg);"></div>
                            <div class="blog-content">
                                <span class="date">15 January, 2021</span>
                                <h5><a href="blogdetails.html">New Remote Workers Visible To Security.</a></h5>
                                <p>Essentially It has survived not only five centuries typesetting remaining was the release more recent.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>