 <!-- START Page Banner -->
 <section class="page-banner">
     <div class="container">
         <div class="banner-content text-center">
             <h2>Service Details</h2>
             <div class="page-breadcrumb">
                 <nav aria-label="breadcrumb">
                     <ol class="breadcrumb">
                         <li class="breadcrumb-item"><a href="index-2.html">Home</a></li>
                         <li class="breadcrumb-item active" aria-current="page">Pages</li>
                     </ol>
                 </nav>
             </div>
         </div>
     </div>
 </section>
 <!-- END Page Banner -->

 <!-- START Service Details Content -->
 <section class="service-details pt-120 rpt-100 pb-115 rpb-95">
     <div class="container">
         <div class="row">
             <div class="col-lg-4">
                 <div class="service-sidebar">
                     <div class="sidebar-widget service-widget">
                         <h4>All Services</h4>
                         <ul>
                             <li><a href="servicedetails.html">Web Development</a></li>
                             <li><a href="servicedetails.html">Data Management</a></li>
                             <li><a href="servicedetails.html">Cyber Security</a></li>
                             <li><a href="servicedetails.html">Software Development</a></li>
                             <li><a href="servicedetails.html">Cloud Management</a></li>
                         </ul>
                     </div>
                     <div class="sidebar-widget service-video-widget text-center">
                         <a class="video-play mfp-iframe" href="https://www.youtube.com/watch?v=aFWhf2wjJYo&amp;list=PLUoqTnNH-2XxOt7UsKlTqbfrA2ucGosCR">
                             <i class="icofont-ui-play"></i>
                         </a>
                         <div class="project-text">
                             <h4>Have any project in you mind?</h4>
                             <a href="callto:00669783">+00 66 97 83</a>
                         </div>
                     </div>
                 </div>
             </div>
             <div class="col-lg-8">
                 <div class="service-details-content">
                     <div class="service-details-image">
                         <img src="<?php echo $iniObj->UIPath; ?>/images/service/service-details.jpg" alt="Service Details Image" />
                         <a class="video-play mfp-iframe" href="https://www.youtube.com/watch?v=aFWhf2wjJYo&amp;list=PLUoqTnNH-2XxOt7UsKlTqbfrA2ucGosCR">
                             <i class="icofont-ui-play"></i>
                         </a>
                     </div>
                     <h2>IT Management Service</h2>
                     <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the ind ustry's standard dummy text ever since the 1500s, when an unknown printer took and galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages.</p>
                     <blockquote>It has survived not only five centuries, but also the leap into the typesetting, remaining essentially unchanged. It was popular of the reease and more recent. Lorem Ipsum is simply dummy text of the printing and typesetting industry.</blockquote>
                     <div class="work-part-content">
                         <div class="row align-items-center">
                             <div class="col-md-6">
                                 <div class="work-left">
                                     <div class="work-image">
                                         <img src="<?php echo $iniObj->UIPath; ?>/images/service/work-img1.png" alt="Work Image" />
                                     </div>
                                     <div class="work-image-two">
                                         <img src="<?php echo $iniObj->UIPath; ?>/images/service/work-img2.png" alt="Work Image" />
                                     </div>
                                 </div>
                             </div>
                             <div class="col-md-6">
                                 <div class="work-content">
                                     <h2>How it work?</h2>
                                     <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the ind ustry's standard dummy text ever since the 1500s, when an unknown printer took and galley of type and scrambled it to make a type specimen book.</p>
                                     <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the ind ustry's standard dummy text ever since the 1500s, when an unknown printer took and galley of type and scrambled it to make a type specimen book.</p>
                                     <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the ind ustry's standard dummy.</p>
                                 </div>
                             </div>
                         </div>
                     </div>
                     <h2>Help challenge critical activities</h2>
                     <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the ind ustry's standard dummy text ever since the 1500s, when an unknown printer took and galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages.</p>
                     <blockquote>It has survived not only five centuries, but also the leap into the typesetting, remaining essentially unchanged. It was popular of the reease and more recent. Lorem Ipsum is simply dummy text of the printing and typesetting industry.</blockquote>
                     <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the ind ustry's standard dummy text ever since the 1500s, when an unknown printer took and galley of type and scrambled it to make a type specimen book.</p>
                 </div>
             </div>
         </div>
     </div>
 </section>
 <!-- END Service Details Content -->

 <!-- START Call To Action -->
 <section class="cta-section bg-white">
     <div class="container">
         <div class="contact-withus">
             <div class="row">
                 <div class="col-lg-7">
                     <div class="contact-withus-content">
                         <h3>Contact With Us.<br /> To Require a Detailed Analysis of Your Plan.</h3>
                     </div>
                 </div>
                 <div class="col-lg-5">
                     <div class="contact-withus-num">
                         <a class="contact-number" href="callto:0095788394">+00 95 788 394</a>
                         <a href="contact.html" class="btn theme-btn">Contact Today<i class="icofont-double-right"></i></a>
                     </div>
                 </div>
             </div>
         </div>
     </div>
 </section>
 <!-- END Call To Action -->

 <!-- START Team Section -->
 <section class="team-section pt-110 rpt-90 pb-120 rpb-60">
     <div class="container">
         <div class="row">
             <div class="col-12">
                 <div class="section-title text-center">
                     <span>Team Members</span>
                     <h2>Our Professional<br /> Team Members</h2>
                 </div>
             </div>
         </div>
         <div class="team-wrap">
             <div class="border-shap"></div>
             <div class="team-member">
                 <div class="member-image">
                     <img src="<?php echo $iniObj->UIPath; ?>/images/team/team-member1.jpg" alt="Team Member Image" />
                 </div>
                 <div class="member-desc">
                     <h5>Sharyl Etheridge</h5>
                     <span>Consultant Officer</span>
                 </div>
             </div>
             <div class="team-member">
                 <div class="member-image">
                     <img src="<?php echo $iniObj->UIPath; ?>/images/team/team-member2.jpg" alt="Team Member Image" />
                 </div>
                 <div class="member-desc">
                     <h5>Brittaney Hickson</h5>
                     <span>Web Developer</span>
                 </div>
             </div>
             <div class="team-member">
                 <div class="member-image">
                     <img src="<?php echo $iniObj->UIPath; ?>/images/team/team-member3.jpg" alt="Team Member Image" />
                 </div>
                 <div class="member-desc">
                     <h5>Rosalina Sheldon</h5>
                     <span>UI Designer</span>
                 </div>
             </div>
         </div>
     </div>
 </section>
 <!-- END Team Section -->